POST http://localhost:5050/api/v1/auth/signup
content-type: application/json

{
    "firstName": "James",
    "lastName": "Bright",
    "email": "james@bright.com",
    "password": "newtestpassword1234",
    "roles": ["TRAINER"]
}

###

POST http://localhost:5050/api/v1/auth/signin
content-type: application/json

{
    "email": "james@bright.com",
    "password": "newtestpassword1234"
}

###

GET http://localhost:5050/api/v1/users/profile
content-type: application/json
authorization: token xxx

###

POST http://localhost:5050/api/v1/users/profile
content-type: application/json
authorization: token xxx

{
    "firstName": "James",
    "lastName": "Bright",
    "email": "james@bright.com",
    "password": "newtestpassword1234"
}

###

POST http://localhost:5050/api/v1/coursetypes
content-type: application/json
authorization: token xxx

{
    "name": "Intensive course",
    "courseDuration": 10,
    "unitDuration": 4
}

###

GET http://localhost:5050/api/v1/coursetypes
content-type: application/json
authorization: token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVmNWNlNmYyN2QyYThkMWRhOTI0ZjMzMyIsInJvbGVzIjpbIlRSQUlORVIiLCJBRE1JTiJdLCJpYXQiOjE1OTk5MjU5ODcsImV4cCI6MTYwMDAxMjM4N30.gsx8PMlp1orM9ojFgmaaUr0iaFAL5ZI4U3zKTJuNG38