POST http://localhost:5050/api/v1/auth/signup
content-type: application/json

{
    "firstName": "James",
    "lastName": "Bright",
    "email": "james@bright.com",
    "password": "newtestpassword1234",
    "roles": ["TRAINER"]
}

###

POST http://localhost:5050/api/v1/auth/signin
content-type: application/json

{
    "email": "john@doe.com",
    "password": "test1234"
}

###

GET http://localhost:5050/api/v1/users/profile
content-type: application/json
authorization: token xxx

###

POST http://localhost:5050/api/v1/users/profile
content-type: application/json
authorization: token xxx

{
    "firstName": "James",
    "lastName": "Bright",
    "email": "james@bright.com",
    "password": "newtestpassword1234"
}

###

POST http://localhost:5050/api/v1/coursetypes
content-type: application/json
authorization: token xxx

{
    "name": "Easy course 3",
    "courseDuration": 10,
    "unitDuration": 4
}

###

GET http://localhost:5050/api/v1/coursetypes
content-type: application/json
authorization: token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVmNWNlNmYyN2QyYThkMWRhOTI0ZjMzMyIsInJvbGVzIjpbIlRSQUlORVIiLCJBRE1JTiJdLCJpYXQiOjE2MDAxODc1NDYsImV4cCI6MTYwMDI3Mzk0Nn0.G7hcKfIH7uigw7Xxg_GEgJy5DQL7gSGXjYt2pUBOIzs

###

POST http://localhost:5050/api/v1/coursetypes/5f60ea70f080e90ba668b5fa
content-type: application/json
authorization: token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVmNWNlNmYyN2QyYThkMWRhOTI0ZjMzMyIsInJvbGVzIjpbIlRSQUlORVIiLCJBRE1JTiJdLCJpYXQiOjE2MDAxODc1NDYsImV4cCI6MTYwMDI3Mzk0Nn0.G7hcKfIH7uigw7Xxg_GEgJy5DQL7gSGXjYt2pUBOIzs

{
    "name": "New Name"
}

###

DELETE http://localhost:5050/api/v1/coursetypes/5f60ea70f080e90ba668b5fa
content-type: application/json
authorization: token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVmNWNlNmYyN2QyYThkMWRhOTI0ZjMzMyIsInJvbGVzIjpbIlRSQUlORVIiLCJBRE1JTiJdLCJpYXQiOjE2MDAxODc1NDYsImV4cCI6MTYwMDI3Mzk0Nn0.G7hcKfIH7uigw7Xxg_GEgJy5DQL7gSGXjYt2pUBOIzs