POST http://localhost:5050/api/v1/auth/signup
content-type: application/json

{
    "firstName": "John",
    "lastName": "Doe",
    "email": "john@doe.com",
    "password": "test1234"
}

###

POST http://localhost:5050/api/v1/auth/signin
content-type: application/json

{
    "email": "john@doe.com",
    "password": "test1234"
}

###

GET http://localhost:5050/api/v1/users/profile
content-type: application/json
authorization: token xxx

###

POST http://localhost:5050/api/v1/users/profile
content-type: application/json
authorization: token xxx

{
    "firstName": "James",
    "lastName": "Bright",
    "email": "james@bright.com",
    "password": "newtestpassword1234"
}